python run_text_classification.py \
  --model_name_or_path bert-base-uncased \
  --ensemble_type biased_attention_dynamic_add \
  --ensemble_ratio 0.1 \
  --ensemble_layer_num 12 \
  --model_stage train_ensemble \
  --train_file ../fever_train_preprocessed.json \
  --validation_file ../fever_dev_preprocessed.json \
  --do_train \
  --do_eval \
  --max_seq_length 128 \
  --per_device_train_batch_size 32 \
  --per_device_eval_batch_size 32 \
  --learning_rate 2e-5 \
  --num_train_epochs 5 \
  --evaluation_strategy epoch \
  --save_strategy epoch \
  --load_best_model_at_end \
  --metric_for_best_model accuracy \
  --greater_is_better true \
  --output_dir outputs \
  --seed 42